/**
 * AI ORCHESTRATION PLATFORM
 * Standard Error Codes
 */

export enum ErrorCode {
  UNKNOWN = 'UNKNOWN',

  VALIDATION_ERROR = 'VALIDATION_ERROR',

  UNAUTHORIZED = 'UNAUTHORIZED',

  FORBIDDEN = 'FORBIDDEN',

  NOT_FOUND = 'NOT_FOUND',

  DATABASE_ERROR = 'DATABASE_ERROR',

  AI_PROVIDER_ERROR = 'AI_PROVIDER_ERROR',

  CONFIG_ERROR = 'CONFIG_ERROR',

  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
